### ISSUE TITLE
Scout or scoutd module...

### ISSUE THREAD

**Issue by justicel** [scoutapp/puppet-scout#14]
I submitted a pull request a while back to fix for the namespacing issues with the scout/scoutd gem. Someone apparently reverted it: https://github.com/scoutapp/puppet-scout/commit/9e1f006149a17fcedb1454e58f4a7fe67064fc56

The module on puppet forge is 'scout', not 'scoutd'. Either the naming on the forge needs to be changed to match the Modulefile, or the module needs to be re-named back to 'scout' in the Modulefile. Not doing this will break compatibility with module management solutions like librarian-puppet. I'm not sure how well r10k will deal with it, but I highly, highly, highly suggest that it be made to work correctly with librarian-puppet as that's the core module management solution at this point.

**Comment by dlanderson** [comment]
Hi @justicel - we have two modules on puppetforge:
[scoutapp/scoutd](https://forge.puppetlabs.com/scoutapp/scoutd) for the scoutd/go version which is now our recommended/default agent
and [scoutapp/scout](https://forge.puppetlabs.com/scoutapp/scout) for the old cron version.

The module/init.pp names should match the puppetforge names, depending on which you use. Let me know if you're still seeing a mismatch
