### ISSUE TITLE
release updated version

### ISSUE THREAD

**Issue by markwellis** [scoutapp/puppet-scout#16]
Can you release the updated version with debian support to puppetforge?

Thanks

**Comment by andre** [comment]
@markwellis sure thing. To confirm, you're using scoutd (our daemon) correct? (as opposed to our older cron-based agent).

**Comment by markwellis** [comment]
Yes, via this module

**Comment by andre** [comment]
@markwellis We've released 0.3.0: https://forge.puppetlabs.com/scoutapp/scoutd/readme. Let us know how it goes.

**Comment by markwellis** [comment]
yep that works, thanks @andre
